DropParties:
  Party1:
    delay-between-items: 2
    drops:
      Item1:
        command: "/give %player% diamond 1"
        message: "&a[DPP] &b%player% &fhas been given 1 &bDiamond&f."
      DoesntMatterWhatTheNameIs:
        command: "/nuke %player%"
        message: "&a[DPP]&R Uhoh for %player%!"